language: ruby
sudo: false
before_install:
  # For testing purposes:
  - git config --global user.name "Samuel Williams"
  - git config --global user.email "samuel@oriontransfer.net"
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - 2.4.0
  - rbx-2
env: COVERAGE=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: "rbx-2"
